### ISSUE TITLE
Does this plugin work with blocks? 

### ISSUE THREAD

**Issue by timothyachumba** [rasteiner/k3-whenquery#11]
I can't seem to get this plugin to work when i used it with block fields. It seems to work with all other fields, any thoughs?

**Comment by rasteiner** [comment]
Note to me:

This is correct. The `BlocksField` and `LayoutsField` are special cases in Kirby. They're represented as `FieldClass`es, not configuration arrays like the other fields use. Because of this the list of properties that is sent to the browser is hardcoded (see [`props` function](https://github.com/getkirby/kirby/blob/a22394035c7f0125e43ef9f3832f4f0e3134f693/src/Form/Field/BlocksField.php#L128-L138)). 

Can probably be solved by extending / overwriting `BlocksField` and `LayoutsField` to manually add a `whenQuery` prop to:
 - the props function
 - as class field
 - as getter / setter functions

**Comment by rasteiner** [comment]
fixed in [release 0.3.0](https://github.com/rasteiner/k3-whenquery/releases/tag/0.3.0)
